### ISSUE TITLE
JDKmodifiy修改之后的rt.jar 无法加载

### ISSUE THREAD

**Issue by fenfei331** [asmjmp0/appdbg-JDK#1]
io 重定向功能需要JDKmodifiy中生成的 rt.jar，  

我用生成的rt.jar 替换原版jdk中的rt.jar。  程序就无法运行了
<img width="1135" alt="error" src="https://user-images.githubusercontent.com/73172605/170812953-d6dfac38-3c51-4a69-8905-42895112dcea.png">

**Comment by asmjmp0** [comment]
嗯嗯，这是我生成rt.jar的代码写的有问题，解压这个rt.jar，在解压文件夹目录下执行 ```jar cvf rt.jar .```重新替换rt.jar就可以了。

**Comment by asmjmp0** [comment]
更新了，重新拉去代码试试哈。
