### ISSUE TITLE
 Account responsible for LFS bandwidth should purchase more data packs to restore access.

### ISSUE THREAD

**Issue by belian001** [asmjmp0/appdbg-JDK#2]
大佬你的文件太大了，下不下来 ，能否提供一个百度网盘连接

**Comment by asmjmp0** [comment]
好的，看样子是带宽超了，我等下把用到git LFS文件放到百度云盘吧。

**Comment by asmjmp0** [comment]
链接: https://pan.baidu.com/s/19xvipAbiWwLIoy-ylSIyNg?pwd=2foe 提取码: 2foe
